# Generated by Django 5.2.5 on 2025-09-05 10:40

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctorprofile_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to=doctors.models.get_doctor_image_path),
        ),
    ]
