# Generated by Django 5.2.5 on 2025-09-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
    ]
