# Generated by Django 5.2.5 on 2025-09-05 12:36

import receptionist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to=receptionist.models.get_receptionist_image_path),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning (8 AM - 2 PM)'), ('Afternoon', 'Afternoon (2 PM - 8 PM)'), ('Night', 'Night (8 PM - 8 AM)')], max_length=50, null=True),
        ),
    ]
