# Generated by Django 5.2.5 on 2025-10-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_receptionistprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionistprofile',
            options={'verbose_name': 'Receptionist Profile', 'verbose_name_plural': 'Receptionist Profiles'},
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='national_id_passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID / Passport Number'),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
