# Generated by Django 5.2.5 on 2025-09-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0002_remove_doctor_user_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill'),
        ),
    ]
