# Generated by Django 5.2.5 on 2025-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Credit/Debit Card'), ('MTN Mobile Money', 'MTN Mobile Money'), ('Airtel Money', 'Airtel Money'), ('Insurance', 'Insurance')], max_length=20, null=True),
        ),
    ]
