# Generated by Django 5.2.5 on 2025-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
