# Generated by Django 5.2.5 on 2025-09-05 10:40

import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_license_number_and_more'),
        ('patients', '0002_remove_doctor_user_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/profile_pictures/default.jpeg', null=True, upload_to=patients.models.get_patient_image_path),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('prescription', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=patients.models.get_medical_report_path)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile')),
            ],
        ),
    ]
